### ISSUE TITLE
Plugin admin link 404s on roots/bedrock

### ISSUE THREAD

**Issue by guichhh** [ideal-postcodes/woocommerce#716]
On a bedrock/roots WordPress setup, the plugin settings link in wp-admin > Plugins returns a 404. I haven't had a chance to look through your code but I'm assuming it must have a hardcoded /wp-admin/ link rather than using get_site_url functions?

Bedrock wp-admin url is usually /wp/wp-admin/ instead of /wp-admin/ but should be an easy fix by using get_admin_url() function or similar.

If I get time later this week I will have a look to see if I can submit a pull request to fix this one.

Do you know if any other hardcoded links exist in the codebase which might affect plugin functionality on a Bedrock install? This one obviously doesn't impact my customers at all but just want to be sure it's the only instance.

Thanks in advance

**Comment by cblanc** [comment]
Thanks for reporting this @guichhh - my colleague @mfilip will look into it this week

**Comment by cblanc** [comment]
Believe this is resolved in 3.5.7
